run: taxforms.py
	python taxes.py

1040.js/forms/f1040.m4:
	git clone https://github.com/b-k/1040.js

taxforms.py: 1040.js/forms/f1040.m4
	echo "###AUTOGENERATED via m4. Please edit the sources." > taxforms.py
	m4 -P macros/pull_fns.m4 1040.js/forms/f*.m4 1040.js/forms/s*.m4 >> taxforms.py
	m4 -P macros/pull_deps.m4 1040.js/forms/f*.m4 1040.js/forms/s*.m4 | sed '$$a\'$$'\n'')' >> taxforms.py   #'
	m4 -P macros/pull_nodes.m4 1040.js/forms/f*.m4 1040.js/forms/s*.m4 | sed '$$a\'$$'\n'')' >> taxforms.py  #'

